# Generated by Django 5.1.1 on 2024-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery (images)',
            },
        ),
        migrations.AlterModelOptions(
            name='downloadmaterials',
            options={'verbose_name_plural': 'Download Materials(such as PDFS,... etc)'},
        ),
    ]
